%% Q3
load('mnist_train.mat');
labels = [];
for i = 1:10
    labels = [labels, train_labels == i];
end
%% 

% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by Neural Pattern Recognition app
% Created 30-Apr-2021 05:17:14
%
% This script assumes these variables are defined:
%
%   train_X - input data.
%   labels - target data.

x = train_X'; % input data to present to the network
t = labels';  % target data defining desired network output
              % Samples are Matrix rows

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Scaled conjugate gradient backpropagation.

% Create a Pattern Recognition Network
hiddenLayerSize = [100,100]; % 2 layers in Hidden layer, 100 neurons/layer
net = patternnet(hiddenLayerSize, trainFcn);

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

net.trainParam.lr = 0.05;       % 0 < lr < 1
net.trainParam.epochs = 5000;  % weight updates
net.trainParam.max_fail = 100; % in order to see a wider graph

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y);
tind = vec2ind(t);
yind = vec2ind(y);
percentErrors = sum(tind ~= yind)/numel(tind);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotconfusion(t,y)
%figure, plotroc(t,y)

